Repository Step3-kakao-tech-campus/Team3_BE, pull requests merged in 2023-10, with the labels that each got.

#39 쪽지 API 구현 완료
  src/main/java/com/bungaebowling/server/message/Message.java
  src/main/java/com/bungaebowling/server/message/controller/MessageController.java
  src/main/java/com/bungaebowling/server/message/dto/MessageRequest.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/message/repository/MessageRepository.java
  src/main/java/com/bungaebowling/server/message/service/MessageService.java
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
Labels: Priority: Medium, Type: Enhancement

#40 점수 CRUD 구현
  .gitignore
  build.gradle
  src/main/java/com/bungaebowling/server/ServerApplication.java
  src/main/java/com/bungaebowling/server/_core/config/AwsS3Config.java
  src/main/java/com/bungaebowling/server/_core/config/MultipartConfig.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/dto/ScoreResponse.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/resources/application-aws.yml.example
  src/main/resources/application-local.yml
  src/main/resources/application-product.yml
  src/main/resources/application.yml
  src/main/resources/ddl.sql
Labels: Priority: Medium, Type: Enhancement

#42 모집글 피드백 반영
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostRequest.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
Labels: Priority: Medium, Type: Maintenance

#45 부산대_3조_번개볼링_5주차
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/bungaebowling/server/ServerApplication.java
  src/main/java/com/bungaebowling/server/_core/config/AwsS3Config.java
  src/main/java/com/bungaebowling/server/_core/config/MultipartConfig.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
  src/main/java/com/bungaebowling/server/comment/Comment.java
  src/main/java/com/bungaebowling/server/comment/controller/CommentController.java
  src/main/java/com/bungaebowling/server/comment/dto/CommentRequest.java
  src/main/java/com/bungaebowling/server/comment/dto/CommentResponse.java
  src/main/java/com/bungaebowling/server/comment/repository/CommentRepository.java
  src/main/java/com/bungaebowling/server/comment/service/CommentService.java
  src/main/java/com/bungaebowling/server/message/Message.java
  src/main/java/com/bungaebowling/server/message/controller/MessageController.java
  src/main/java/com/bungaebowling/server/message/dto/MessageRequest.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/message/repository/MessageRepository.java
  src/main/java/com/bungaebowling/server/message/service/MessageService.java
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostRequest.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/dto/ScoreResponse.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/rate/repository/UserRateRepository.java
  src/main/resources/application-aws.yml.example
  src/main/resources/application-local.yml
  src/main/resources/application-product.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/ddl.sql
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
Labels: Type: Maintenance, Type: Question

#41 프로필, 유저 기록, 참여 기록, 신청 여부 API 구현
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/applicant/Applicant.java
  src/main/java/com/bungaebowling/server/applicant/controller/ApplicantController.java
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
  src/main/java/com/bungaebowling/server/user/rate/UserRate.java
  src/main/java/com/bungaebowling/server/user/rate/repository/UserRateRepository.java
  src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/ddl.sql
Labels: Priority: Medium, Type: Enhancement

#53 신청 상태 조회 api에 applicant id 추가
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
Labels: Priority: High, Type: Bug

#48 점수 등록, 수정 API 수정
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/dto/PostRequest.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
Labels: Priority: Low, Type: Enhancement, Type: Maintenance

#54 쪽지API 대화방목록조회 수정
  src/main/java/com/bungaebowling/server/message/controller/MessageController.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/message/repository/MessageRepository.java
  src/main/java/com/bungaebowling/server/message/service/MessageService.java
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
Labels: Priority: Medium, Type: Enhancement, Type: Maintenance

#60 참여 기록 조회, 신청자 목록 버그 수정
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
Labels: Priority: High, Type: Bug

#64 CustomExeption 수정 완료
  src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/CustomException.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception400.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception401.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception403.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception404.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/server/Exception500.java
  src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
  src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
  src/main/java/com/bungaebowling/server/_core/utils/ApiUtils.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
  src/main/java/com/bungaebowling/server/city/service/CityService.java
  src/main/java/com/bungaebowling/server/comment/service/CommentService.java
  src/main/java/com/bungaebowling/server/message/service/MessageService.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
Labels: Priority: Low, Type: Maintenance

#57 부산대_3조_번개볼링_6주차
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/applicant/Applicant.java
  src/main/java/com/bungaebowling/server/applicant/controller/ApplicantController.java
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantRequest.java
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
  src/main/java/com/bungaebowling/server/message/controller/MessageController.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/message/repository/MessageRepository.java
  src/main/java/com/bungaebowling/server/message/service/MessageService.java
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostRequest.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
  src/main/java/com/bungaebowling/server/user/rate/UserRate.java
  src/main/java/com/bungaebowling/server/user/rate/repository/UserRateRepository.java
  src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/ddl.sql
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
Labels: Type: Maintenance, Type: Question

#70 점수 등록 API 수정
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
Labels: Priority: Low, Type: Bug

#77 쪽지 목록 조회 api 누락 항목 추가 완료
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
Labels: Priority: High, Type: Bug

#75 기존의 메시지 repository test의 더미데이터를 teardown을 사용하도록 변경
  src/main/resources/data.sql
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Priority: Medium, Type: Maintenance

#81 유저 통합 테스트 완성
  src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Maintenance

#85 점수 API 개선
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
Labels: Priority: High, Type: Bug, Type: Enhancement, Type: Maintenance

#89 open api spec(Swagger UI)를 사용한 api 문서 생성
  .gitignore
  build.gradle
  src/main/resources/application.yml
  src/main/resources/static/docs/.gitkeep
  src/test/java/com/bungaebowling/server/ApiTag.java
  src/test/java/com/bungaebowling/server/ControllerTestConfig.java
  src/test/java/com/bungaebowling/server/GeneralApiResponseSchema.java
  src/test/java/com/bungaebowling/server/ServerApplicationTests.java
  src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Documentation, Type: Enhancement

#92 environment variable을 활용하여 실행 profile 별 yml 분리
  .env.example
  .gitignore
  src/main/resources/application-aws.yml.example
  src/main/resources/application-local.yml
  src/main/resources/application-mysql.yml.example
  src/main/resources/application-private.yml.example
  src/main/resources/application-product.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Maintenance

#74 부산대_3조_번개볼링_7주차
  src/main/java/com/bungaebowling/server/ServerApplication.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/CustomException.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception400.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception401.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception403.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception404.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/server/Exception500.java
  src/main/java/com/bungaebowling/server/_core/security/CustomUserDetailsService.java
  src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
  src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
  src/main/java/com/bungaebowling/server/_core/utils/ApiUtils.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/_core/utils/CursorRequest.java
  src/main/java/com/bungaebowling/server/applicant/Applicant.java
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantRequest.java
  src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
  src/main/java/com/bungaebowling/server/city/dto/CityResponse.java
  src/main/java/com/bungaebowling/server/city/service/CityService.java
  src/main/java/com/bungaebowling/server/comment/dto/CommentRequest.java
  src/main/java/com/bungaebowling/server/comment/dto/CommentResponse.java
  src/main/java/com/bungaebowling/server/comment/service/CommentService.java
  src/main/java/com/bungaebowling/server/message/Message.java
  src/main/java/com/bungaebowling/server/message/controller/MessageController.java
  src/main/java/com/bungaebowling/server/message/dto/MessageRequest.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/message/repository/MessageRepository.java
  src/main/java/com/bungaebowling/server/message/service/MessageService.java
  src/main/java/com/bungaebowling/server/post/Post.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostRequest.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/dto/ScoreResponse.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
  src/main/java/com/bungaebowling/server/user/rate/UserRate.java
  src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/application-test.yml
  src/main/resources/data.sql
  src/main/resources/ddl.sql
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/ServerApplicationTests.java
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Maintenance, Type: Question
