Repository Step3-kakao-tech-campus/Team3_BE, pull requests merged in 2023-11, with the labels that each got.

#108 댓글 조회 테스트 코드 작성 및 문서화 + 기타 버그 수정
  src/main/java/com/bungaebowling/server/comment/service/CommentService.java
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralParameters.java
  src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
  src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Documentation, Type: Maintenance

#109 댓글 api 테스트 및 문서 작성 완료
  src/main/java/com/bungaebowling/server/comment/Comment.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
  src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Documentation, Type: Maintenance

#111 비밀번호 관련 API 추가
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
Labels: Priority: Medium, Type: Enhancement

#112 8-9주차 개발 내역 정리
  .env.example
  .gitignore
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/configs/create.sql
  k8s/configs/default.conf
  k8s/create-k8s-secret.sh
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  k8s/redis.yaml
  src/main/java/com/bungaebowling/server/_core/config/Configs.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
  src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/comment/Comment.java
  src/main/java/com/bungaebowling/server/comment/service/CommentService.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/place/controller/PlaceController.java
  src/main/java/com/bungaebowling/server/place/dto/PlaceResponse.java
  src/main/java/com/bungaebowling/server/place/service/PlaceService.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/application-aws.yml.example
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-mysql.yml.example
  src/main/resources/application-private.yml.example
  src/main/resources/application-product.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/static/docs/.gitkeep
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/ControllerTestConfig.java
  src/test/java/com/bungaebowling/server/ServerApplicationTests.java
  src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralParameters.java
  src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
  src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Maintenance

#114 CORS 설정 하드코딩하여 직접 추가
  src/main/java/com/bungaebowling/server/_core/config/Configs.java
Labels: Type: Maintenance

#118 s3 관련 프록시 설정 및 프론트 배포
  .gitignore
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/create-k8s-secret.sh
  k8s/frontend.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  src/main/java/com/bungaebowling/server/_core/config/AwsS3Config.java
  src/main/java/com/bungaebowling/server/_core/config/Configs.java
  src/main/java/com/bungaebowling/server/_core/config/RestTemplateConfig.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-product.yml
  src/main/resources/application-test.yml
Labels: Priority: High, Type: Bug, Type: Enhancement, Type: Maintenance

#116 메시지 테스트 및 API문서화 완료
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/message/controller/MessageControllerTest.java
  src/test/java/com/bungaebowling/server/message/repository/MessageRepositoryTest.java
Labels: Priority: Medium

#121 참여 기록 조회, 프로필 수정 버그 수정
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
  src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
Labels: Priority: Medium, Type: Bug

#122 허용된 파일 확장자 리스트를 상수로 관리
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
Labels: Type: Maintenance

#124 점수 관련 버그 수정
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
Labels: Priority: Low, Type: Bug, Type: Maintenance

#126 Post 테스트 및 문서화 완료
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/comment/repository/CommentRepository.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/user/rate/repository/UserRateRepository.java
  src/test/java/com/bungaebowling/server/message/controller/MessageControllerTest.java
  src/test/java/com/bungaebowling/server/post/controller/PostControllerTest.java
Labels: Priority: Medium, Type: Bug, Type: Maintenance

#125 ScoreController api 문서화 완료
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/score/controller/ScoreControllerTest.java
Labels: Type: Documentation, Type: Maintenance

#120 ApplicantController api 문서화 완료
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
  src/test/java/com/bungaebowling/server/applicant/controller/ApplicantControllerTest.java
Labels: Type: Documentation, Type: Maintenance

#127 비밀번호 API 테스트 및 문서화 완료
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Priority: Medium, Type: Documentation, Type: Maintenance

#115 부산대_3조_번개볼링_9주차
  .env.example
  .gitignore
  Dockerfile
  build.gradle
  k8s/backend.yaml
  k8s/configs/create.sql
  k8s/configs/default.conf
  k8s/create-k8s-secret.sh
  k8s/kustomization.yaml
  k8s/mysql.yaml
  k8s/nginx.yaml
  k8s/redis.yaml
  src/main/java/com/bungaebowling/server/_core/config/Configs.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
  src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/comment/Comment.java
  src/main/java/com/bungaebowling/server/comment/service/CommentService.java
  src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
  src/main/java/com/bungaebowling/server/place/controller/PlaceController.java
  src/main/java/com/bungaebowling/server/place/dto/PlaceResponse.java
  src/main/java/com/bungaebowling/server/place/service/PlaceService.java
  src/main/java/com/bungaebowling/server/post/controller/PostController.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/User.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/application-aws.yml.example
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-mysql.yml.example
  src/main/resources/application-private.yml.example
  src/main/resources/application-product.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/static/docs/.gitkeep
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/ControllerTestConfig.java
  src/test/java/com/bungaebowling/server/ServerApplicationTests.java
  src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
  src/test/java/com/bungaebowling/server/_core/commons/GeneralParameters.java
  src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
  src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
  src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Maintenance, Type: Question

#129 CI/CD 파이프라인 구축
  .github/workflow/build_test.yml
  .github/workflow/deploy.yml
  nohup.sh
Labels: Type: Enhancement

#133 SMTP를 통한 이메일 인증 구현
  flask/Dockerfile
  flask/app.py
  flask/start.sh
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/create-k8s-secret.sh
  k8s/frontend.yaml
  src/main/java/com/bungaebowling/server/_core/config/AwsS3Config.java
  src/main/java/com/bungaebowling/server/_core/config/MailConfig.java
  src/main/java/com/bungaebowling/server/_core/config/RestTemplateConfig.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-product.yml
  src/main/resources/application-test.yml
Labels: Priority: High, Type: Bug, Type: Maintenance

#131 리드미 작성
  .env.example
  README.md
  docs/번개볼링_기획안_v2.3.pptx
Labels: Type: Documentation

#134 파일명 작성 함수 수정
  k8s/frontend.yaml
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
Labels: Priority: Low, Type: Bug, Type: Maintenance

#136 10주차 개발 내역 정리
  .env.example
  .github/workflows/build_test.yml
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  docs/번개볼링_기획안_v2.3.pptx
  flask/Dockerfile
  flask/app.py
  flask/start.sh
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/create-k8s-secret.sh
  k8s/frontend.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mysql.yaml
  nohup.sh
  src/main/java/com/bungaebowling/server/_core/config/AwsS3Config.java
  src/main/java/com/bungaebowling/server/_core/config/Configs.java
  src/main/java/com/bungaebowling/server/_core/config/MailConfig.java
  src/main/java/com/bungaebowling/server/_core/config/RestTemplateConfig.java
  src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
  src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
  src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
  src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
  src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
  src/main/java/com/bungaebowling/server/comment/repository/CommentRepository.java
  src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
  src/main/java/com/bungaebowling/server/post/service/PostService.java
  src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
  src/main/java/com/bungaebowling/server/score/Score.java
  src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
  src/main/java/com/bungaebowling/server/score/repository/ScoreRepository.java
  src/main/java/com/bungaebowling/server/score/service/ScoreService.java
  src/main/java/com/bungaebowling/server/user/controller/UserController.java
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/rate/repository/UserRateRepository.java
  src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
  src/main/resources/application-deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-product.yml
  src/main/resources/application-test.yml
  src/main/resources/test_db/teardown.sql
  src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
  src/test/java/com/bungaebowling/server/applicant/controller/ApplicantControllerTest.java
  src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
  src/test/java/com/bungaebowling/server/message/controller/MessageControllerTest.java
  src/test/java/com/bungaebowling/server/message/repository/MessageRepositoryTest.java
  src/test/java/com/bungaebowling/server/post/controller/PostControllerTest.java
  src/test/java/com/bungaebowling/server/score/controller/ScoreControllerTest.java
  src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java
Labels: Type: Enhancement, Type: Maintenance

#137 프론트 docker iamge 변경
  k8s/frontend.yaml
Labels: Priority: Low, Type: Maintenance

#140 이메일 전송 양식 변경
  src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
  src/main/java/com/bungaebowling/server/user/service/UserEmailCreator.java
  src/main/java/com/bungaebowling/server/user/service/UserService.java
Labels: Type: Enhancement
